version: '3'
services:
  mkvtoolnix:
    image: jlesage/mkvtoolnix
    environment:
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    ports:
      - "5800:5800"
    volumes:
      - "./mkvtoolnix:/config:rw"
      - "/home/user:/storage:rw"